force-app/main/default/objects/Pizza__c/fields/Toppings__c.field-meta.xml
<CustomField>
    <fullName>Toppings__c</fullName>
    <description>The toppings of the pizza - select all that apply.</description>
    <label>Toppings</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pepperoni</fullName>
            </value>
            <value>
                <fullName>Bacon</fullName>
            </value>
            <value>
                <fullName>Sausage</fullName>
            </value>
            <value>
                <fullName>Pineapple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shopping_Cart__c/fields/Store_Location__c.field-meta.xml
<CustomField>
    <fullName>Store_Location__c</fullName>
    <label>Store Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1600 Pennsylvania Ave NW, Washington, DC</fullName>
                <default>true</default>
                <label>1600 Pennsylvania Ave NW, Washington, DC</label>
            </value>
            <value>
                <fullName>5 Avenue Anatole France, Paris, FR 75007</fullName>
            </value>
            <value>
                <fullName>Place de la Louve 6, 7100 La Louviere, Belgium</fullName>
            </value>
            <value>
                <fullName>24 Maggio 30, Pisa, IT 56127</fullName>
            </value>
            <value>
                <fullName>Liberty Island, New York City, NY 10004</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CheckoutHelperApexController.cls
public class CheckoutHelperApexController 
{
    public static Shopping_Cart__C thisCart;
    
    @auraEnabled
    public static void insertCart()
    {
        //contact thisContact = CustomController.getContactInfo();
        //user thisUser = CustomController.getUserInfo();
        
        thisCart = new Shopping_Cart__c(/*Store_Location__c = thisUser.default_location__c, Account__c = thisContact.AccountId*/);
        insert thisCart;
        
        
    }
    
    @auraEnabled
    public static void makePizza(List<String> size, List<String> toppings)
    {
        system.debug('help');
        
        //List<Pizza__C> orderPizzas = new List<Pizza__C>();

        Shopping_cart__c thisCart = [SELECT id FROM Shopping_cart__c ORDER BY createddate DESC LIMIT 1];
        
        for(Integer i = 0; i < size.size(); i++){
            Pizza__c pizzaToAdd = new Pizza__C();
            pizzaToAdd.Size__c = size[i];
            system.debug('size added');
            pizzaToAdd.Toppings__c = toppings[i];
            system.debug('toppings added');
            pizzaToAdd.Shopping_Cart__c = thisCart.Id;
            system.debug('cart added');
            
            insert pizzaToAdd;
        }
        //system.debug('order pizzas: ' + orderPizzas);
        //insert orderPizzas;
    }
    
}