force-app/main/default/objects/Pizza__c/fields/Toppings__c.field-meta.xml
<CustomField>
    <fullName>Toppings__c</fullName>
    <description>The toppings of the pizza - select all that apply.</description>
    <label>Toppings</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pepperoni</fullName>
            </value>
            <value>
                <fullName>Bacon</fullName>
            </value>
            <value>
                <fullName>Sausage</fullName>
            </value>
            <value>
                <fullName>Pineapple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shopping_Cart__c/fields/Store_Location__c.field-meta.xml
<CustomField>
    <fullName>Store_Location__c</fullName>
    <label>Store Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1600 Pennsylvania Ave NW, Washington, DC</fullName>
                <default>true</default>
                <label>1600 Pennsylvania Ave NW, Washington, DC</label>
            </value>
            <value>
                <fullName>5 Avenue Anatole France, Paris, FR 75007</fullName>
            </value>
            <value>
                <fullName>Place de la Louve 6, 7100 La Louviere, Belgium</fullName>
            </value>
            <value>
                <fullName>24 Maggio 30, Pisa, IT 56127</fullName>
            </value>
            <value>
                <fullName>Liberty Island, New York City, NY 10004</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HomePizzaApexController.cls
public without sharing class HomePizzaApexController 
{
	@auraEnabled
    public static void placeMLSOrder()
    {
        contact thisContact = CustomController.getContactInfo();
        user currUser = CustomController.getUserInfo();
        Shopping_Cart__C newCart = new Shopping_Cart__C(Store_location__c = currUser.Default_Location__c, Account__c = thisContact.AccountId);
        insert newCart;
        Pizza__C newPizza = new Pizza__C(size__C = 'Extra_Large', Shopping_Cart__C = newCart.id, Toppings__c = 'Pepporoni;Sausage;Bacon');
		insert newPizza;
    }
    
    @auraEnabled
    public static void placeHawaiianOrder()
    {
        contact thisContact = CustomController.getContactInfo();
        user currUser = CustomController.getUserInfo();
		Shopping_Cart__C newCart = new Shopping_Cart__C(Store_location__c = currUser.Default_Location__c, Account__c = thisContact.AccountId);
        insert newCart;
        Pizza__C newPizza = new Pizza__C(size__C = 'Medium', Shopping_Cart__C = newCart.id, Toppings__c = 'Pineapple;Bacon');
		insert newPizza;        
    }
    
    @auraEnabled
    public static void placeHeartAttackOrder()
    {
        contact thisContact = CustomController.getContactInfo();
        user currUser = CustomController.getUserInfo();
        Shopping_Cart__C newCart = new Shopping_Cart__C(Store_location__c = currUser.Default_Location__c, Account__c = thisContact.AccountId);
        insert newCart;
        Pizza__C newPizza = new Pizza__C(size__C = 'Extra_Large', Shopping_Cart__C = newCart.id, Toppings__c = '');
		insert newPizza; 
    }
}